blank_issues_enabled: false
contact_links:
  - name: 💬 Discusiones de la Comunidad
    url: https://github.com/orgs/trucostars/discussions
    about: Haz preguntas generales y participa en la comunidad de trucostars.
